"""
SCRIPT 2 — Train Isolation Forest + Save Model
===============================================
BehaviorVault 2.0 | SuRaksha Cyber Hackathon 2.0

WHAT THIS SCRIPT DOES:
-----------------------
1. Loads behavioral_data.csv (generated by Script 1)
2. Scales features using StandardScaler
3. Trains an Isolation Forest on NORMAL sessions ONLY
4. Evaluates it against all 1200 rows (normal + anomaly)
5. Prints a full classification report + confusion matrix
6. Saves the trained model and scaler to disk

WHY TRAIN ON NORMAL ONLY:
--------------------------
Isolation Forest is an UNSUPERVISED anomaly detection algorithm.
It never sees labels during training. It builds a picture of what
"normal behavior" looks like by randomly partitioning the feature space.
Sessions that are easy to isolate (short path to isolation) = anomalies.
Sessions that need many partitions to isolate = normal.

The "label" column in the CSV is ONLY used in Step 4 (evaluation).

WHY WE NEED THE SCALER:
------------------------
Our 5 features have very different numeric ranges:
  - keystroke_timing_ms : 80–400 (hundreds)
  - touch_pressure      : 0.1–1.0 (decimals)
  - swipe_speed_px_s    : 100–1200 (hundreds)
  - scroll_rhythm_ms    : 50–1000 (hundreds)
  - accel_variance      : 0.001–1.0 (small decimals)

Without scaling, the tree splits will be dominated by the features
with large values (keystrokes, swipe speed). StandardScaler transforms
everything to mean=0, std=1, so all features contribute equally.

IMPORTANT: The SAME scaler used in training must be used at inference
time on the mobile app. That's why we save it to scaler.pkl.

HOW TO RUN:
-----------
  python 02_train_model.py

REQUIRES:
---------
  behavioral_data.csv  (output of 01_generate_data.py)

OUTPUT FILES:
-------------
  isolation_forest.pkl  — the trained model (used in Script 3)
  scaler.pkl            — the fitted scaler  (used in Script 3)
  evaluation_report.txt — accuracy, precision, recall, confusion matrix
"""

import numpy as np
import pandas as pd
import pickle
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (classification_report, confusion_matrix,
                             roc_auc_score)


# ── Feature columns (must match what the mobile app sends) ───────────────────
FEATURES = [
    "keystroke_timing_ms",
    "touch_pressure",
    "swipe_speed_px_s",
    "scroll_rhythm_ms",
    "accel_variance"
]


# ─────────────────────────────────────────────────────────────────────────────
# STEP 1 — Load data
# ─────────────────────────────────────────────────────────────────────────────
print("=" * 55)
print("STEP 1 — Loading behavioral_data.csv")
print("=" * 55)

df = pd.read_csv("behavioral_data.csv")
print(f"  Total rows loaded : {len(df)}")
print(f"  Normal  (label=0) : {(df['label']==0).sum()}")
print(f"  Anomaly (label=1) : {(df['label']==1).sum()}")

# Separate features and labels
X = df[FEATURES].values          # shape: (1200, 5)
y = df["label"].values            # shape: (1200,) — only used for evaluation

# Normal-only data for training
X_normal = df[df["label"] == 0][FEATURES].values   # shape: (1000, 5)
print(f"\n  Training will use {len(X_normal)} normal sessions only.")


# ─────────────────────────────────────────────────────────────────────────────
# STEP 2 — Scale features
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 55)
print("STEP 2 — Scaling features with StandardScaler")
print("=" * 55)

scaler = StandardScaler()

# CRITICAL: fit the scaler on NORMAL data only.
# If we fit on the full dataset including anomalies, the mean/std will be
# slightly skewed toward anomaly values — we don't want that.
scaler.fit(X_normal)

# Transform all data (for evaluation) and normal data (for training)
X_scaled        = scaler.transform(X)          # all 1200 rows, scaled
X_normal_scaled = scaler.transform(X_normal)   # 1000 normal rows, scaled

print(f"  Scaler fitted on {len(X_normal)} normal sessions.")
print("\n  Feature means (should be ~0.0 for normal data after scaling):")
for i, feat in enumerate(FEATURES):
    mean_after = X_normal_scaled[:, i].mean()
    std_after  = X_normal_scaled[:, i].std()
    print(f"    {feat:<25} mean={mean_after:+.4f}  std={std_after:.4f}")


# ─────────────────────────────────────────────────────────────────────────────
# STEP 3 — Train the Isolation Forest
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 55)
print("STEP 3 — Training Isolation Forest")
print("=" * 55)

# KEY PARAMETERS EXPLAINED:
#
# n_estimators=200
#   Number of isolation trees. More trees = more stable scores.
#   200 is a good balance between accuracy and inference speed.
#   Default is 100; we use 200 because we need reliable on-device scores.
#
# max_samples='auto'
#   How many samples each tree uses. 'auto' = min(256, n_samples).
#   This is intentionally small — isolation trees work better on subsamples.
#
# contamination=0.05
#   The model's assumed fraction of anomalies in production data.
#   We set this to 5% (real-world banking fraud rate estimate).
#   This controls the decision threshold: the score cutoff below which
#   a session is flagged as anomalous.
#   NOTE: This does NOT affect training, only the predict() threshold.
#
# max_features=1.0
#   Each tree considers all 5 features. Fine for 5 features.
#
# random_state=42
#   Reproducibility — same result every run.

model = IsolationForest(
    n_estimators=200,
    max_samples="auto",
    contamination=0.05,
    max_features=1.0,
    random_state=42
)

# Train ONLY on normal sessions
model.fit(X_normal_scaled)
print("  ✅  Model trained on normal sessions.")
print(f"     n_estimators : {model.n_estimators}")
print(f"     contamination: {model.contamination}")
print(f"     n_features   : {model.n_features_in_}")


# ─────────────────────────────────────────────────────────────────────────────
# STEP 4 — Evaluate on all 1200 rows
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 55)
print("STEP 4 — Evaluating model on all 1200 sessions")
print("=" * 55)

# predict() returns:  +1 = normal,  -1 = anomaly
# We remap to:         0 = normal,   1 = anomaly  (to match our labels)
raw_predictions  = model.predict(X_scaled)             # +1 or -1
y_pred           = (raw_predictions == -1).astype(int) # 0 or 1

# decision_function() returns raw anomaly scores (lower = more anomalous)
# We negate so higher score = more anomalous (easier to reason about)
anomaly_scores   = -model.decision_function(X_scaled)  # float array

# Add predictions back to dataframe for inspection
df["anomaly_score"] = anomaly_scores.round(5)
df["predicted"]     = y_pred

# ── Classification report ────────────────────────────────────────────────────
print("\n  Classification Report:")
print("  " + "-" * 50)
report = classification_report(y, y_pred,
                                target_names=["Normal", "Anomaly"],
                                digits=3)
for line in report.splitlines():
    print("  " + line)

# ── Confusion matrix ─────────────────────────────────────────────────────────
cm = confusion_matrix(y, y_pred)
tn, fp, fn, tp = cm.ravel()
print(f"\n  Confusion Matrix:")
print(f"                    Predicted Normal  Predicted Anomaly")
print(f"  Actual Normal   :      {tn:<10}        {fp}")
print(f"  Actual Anomaly  :      {fn:<10}        {tp}")
print(f"\n  True Negatives  (correctly flagged normal) : {tn}")
print(f"  False Positives (normal flagged as anomaly) : {fp}  ← false alarms")
print(f"  False Negatives (anomaly missed)            : {fn}  ← missed attacks")
print(f"  True Positives  (anomaly caught)            : {tp}")

# ── AUC-ROC ──────────────────────────────────────────────────────────────────
auc = roc_auc_score(y, anomaly_scores)
print(f"\n  AUC-ROC Score : {auc:.4f}  (1.0 = perfect, 0.5 = random guess)")

# ── Score distribution ───────────────────────────────────────────────────────
normal_scores  = anomaly_scores[y == 0]
anomaly_scores_only = anomaly_scores[y == 1]
print(f"\n  Anomaly Score Distribution:")
print(f"    Normal  sessions — mean: {normal_scores.mean():.4f}  "
      f"max: {normal_scores.max():.4f}")
print(f"    Anomaly sessions — mean: {anomaly_scores_only.mean():.4f}  "
      f"min: {anomaly_scores_only.min():.4f}")
print(f"\n  A clear gap between these two means = good separation.")


# ─────────────────────────────────────────────────────────────────────────────
# STEP 5 — Save model and scaler
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 55)
print("STEP 5 — Saving model and scaler")
print("=" * 55)

with open("isolation_forest.pkl", "wb") as f:
    pickle.dump(model, f)
print("  ✅  isolation_forest.pkl saved")

with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)
print("  ✅  scaler.pkl saved")

# Also save a sample of scored sessions for manual inspection
df.to_csv("scored_sessions.csv", index=False)
print("  ✅  scored_sessions.csv saved  ← open this to inspect individual scores")


# ─────────────────────────────────────────────────────────────────────────────
# STEP 6 — Write evaluation report to file
# ─────────────────────────────────────────────────────────────────────────────
with open("evaluation_report.txt", "w") as f:
    f.write("BEHAVIORVAULT 2.0 — Isolation Forest Evaluation Report\n")
    f.write("=" * 55 + "\n\n")
    f.write(f"Training set : {len(X_normal)} normal sessions\n")
    f.write(f"Eval set     : {len(X)} total sessions\n\n")
    f.write("Classification Report:\n")
    f.write(report + "\n")
    f.write(f"AUC-ROC Score : {auc:.4f}\n\n")
    f.write(f"Confusion Matrix:\n")
    f.write(f"  TN={tn}  FP={fp}  FN={fn}  TP={tp}\n\n")
    f.write(f"Anomaly Score Distribution:\n")
    f.write(f"  Normal  — mean: {normal_scores.mean():.4f}  "
            f"max: {normal_scores.max():.4f}\n")
    f.write(f"  Anomaly — mean: {anomaly_scores_only.mean():.4f}  "
            f"min: {anomaly_scores_only.min():.4f}\n")

print("  ✅  evaluation_report.txt saved")

print("\n" + "=" * 55)
print("DONE. Files saved:")
print("  isolation_forest.pkl  — trained model")
print("  scaler.pkl            — fitted scaler")
print("  scored_sessions.csv   — all sessions with anomaly scores")
print("  evaluation_report.txt — full metrics")
print("\nNEXT STEP: Run  python 03_export_tflite.py")
print("=" * 55)